/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pyt.gui;

import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URI;
import java.net.URISyntaxException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.DefaultListSelectionModel;
import javax.swing.JList;
import javax.swing.JSpinner;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import pyt.logic.Aeroporto;
import pyt.logic.App;
import pyt.logic.VoloRequest;
import pyt.logic.VoloResponse;


/**
 *
 * @author markp
 */
public class Interfaccia extends javax.swing.JFrame {
    
    ArrayList<VoloResponse> voli_andata = new ArrayList<>();
    ArrayList<VoloResponse> voli_ritorno = new ArrayList<>();
    ArrayList<Aeroporto> aeroporti_andata = new ArrayList<>();
    ArrayList<Aeroporto> aeroporti_ritorno = new ArrayList<>();
    ArrayList<VoloRequest> storico = new ArrayList<>();
    
    public Interfaccia(String token, String username) throws IOException {
        initComponents();
        this.setTitle("Client A - Interfaccia");
        this.token = token;
        username_label.setText(username);
        andata_data_spinner.setEditor(new JSpinner.DateEditor(andata_data_spinner,"dd-MM-yyyy"));
        ritorno_data_spinner.setEditor(new JSpinner.DateEditor(ritorno_data_spinner,"dd-MM-yyyy"));
        setStorico();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        andata_list = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        ritorno_list = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        origine_field = new javax.swing.JTextField();
        origine_cerca_button = new javax.swing.JButton();
        origine_box = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        destinazione_field = new javax.swing.JTextField();
        destinazione_cerca_button = new javax.swing.JButton();
        destinazione_box = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        andata_data_spinner = new javax.swing.JSpinner();
        ritorno_data_label = new javax.swing.JLabel();
        ritorno_data_data_label = new javax.swing.JLabel();
        ritorno_data_spinner = new javax.swing.JSpinner();
        andata_ritorno_check = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        passeggeri_spinner = new javax.swing.JSpinner();
        cerca_button = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        storico_box = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        andata_prenota_button = new javax.swing.JButton();
        ritorno_prenota_button = new javax.swing.JButton();
        andata_volo_label = new javax.swing.JLabel();
        ritorno_volo_label = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        meteo_list = new javax.swing.JList<>();
        log_out_button = new javax.swing.JButton();
        username_label = new javax.swing.JLabel();
        storico_button = new javax.swing.JButton();
        volo_andata_label = new javax.swing.JLabel();
        volo_ritorno_label = new javax.swing.JLabel();
        mappa_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(26, 60, 160));

        andata_list.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        andata_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        andata_list.setToolTipText("Seleziona il voto di andata");
        jScrollPane2.setViewportView(andata_list);

        ritorno_list.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ritorno_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ritorno_list.setToolTipText("Seleziona il volo di ritorno");
        jScrollPane3.setViewportView(ritorno_list);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Da: ");

        origine_field.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        origine_field.setForeground(new java.awt.Color(26, 60, 160));

        origine_cerca_button.setBackground(new java.awt.Color(255, 255, 255));
        origine_cerca_button.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        origine_cerca_button.setForeground(new java.awt.Color(26, 60, 160));
        origine_cerca_button.setText("Cerca");
        origine_cerca_button.setBorderPainted(false);
        origine_cerca_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                origine_cerca_buttonMouseClicked(evt);
            }
        });

        origine_box.setForeground(new java.awt.Color(26, 60, 160));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("A:   ");

        destinazione_field.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        destinazione_field.setForeground(new java.awt.Color(26, 60, 160));

        destinazione_cerca_button.setBackground(new java.awt.Color(255, 255, 255));
        destinazione_cerca_button.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        destinazione_cerca_button.setForeground(new java.awt.Color(26, 60, 160));
        destinazione_cerca_button.setText("Cerca");
        destinazione_cerca_button.setBorderPainted(false);
        destinazione_cerca_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                destinazione_cerca_buttonMouseClicked(evt);
            }
        });

        destinazione_box.setForeground(new java.awt.Color(26, 60, 160));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Andata");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data: ");

        andata_data_spinner.setModel(new javax.swing.SpinnerDateModel());

        ritorno_data_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ritorno_data_label.setForeground(new java.awt.Color(255, 255, 255));
        ritorno_data_label.setText("Ritorno");

        ritorno_data_data_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ritorno_data_data_label.setForeground(new java.awt.Color(255, 255, 255));
        ritorno_data_data_label.setText("Data: ");

        ritorno_data_spinner.setModel(new javax.swing.SpinnerDateModel());

        andata_ritorno_check.setBackground(new java.awt.Color(26, 60, 160));
        andata_ritorno_check.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        andata_ritorno_check.setForeground(new java.awt.Color(255, 255, 255));
        andata_ritorno_check.setSelected(true);
        andata_ritorno_check.setText("Volo andata e ritorno?");
        andata_ritorno_check.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                andata_ritorno_checkMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Numero di passeggeri: ");

        passeggeri_spinner.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        passeggeri_spinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 8, 1));

        cerca_button.setBackground(new java.awt.Color(255, 255, 255));
        cerca_button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cerca_button.setForeground(new java.awt.Color(26, 60, 160));
        cerca_button.setText("Cerca");
        cerca_button.setBorderPainted(false);
        cerca_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerca_buttonMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Storico: ");

        storico_box.setForeground(new java.awt.Color(26, 60, 160));
        storico_box.setToolTipText("Storico delle precedenti ricerche");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Andata");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ritorno");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Meteo (relativo alla giornata di oggi)");

        andata_prenota_button.setBackground(new java.awt.Color(255, 255, 255));
        andata_prenota_button.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        andata_prenota_button.setForeground(new java.awt.Color(26, 60, 160));
        andata_prenota_button.setText("Prenota andata");
        andata_prenota_button.setBorderPainted(false);
        andata_prenota_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                andata_prenota_buttonMouseClicked(evt);
            }
        });

        ritorno_prenota_button.setBackground(new java.awt.Color(255, 255, 255));
        ritorno_prenota_button.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ritorno_prenota_button.setForeground(new java.awt.Color(26, 60, 160));
        ritorno_prenota_button.setText("Prenota ritorno");
        ritorno_prenota_button.setBorderPainted(false);
        ritorno_prenota_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ritorno_prenota_buttonMouseClicked(evt);
            }
        });

        andata_volo_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        andata_volo_label.setForeground(new java.awt.Color(255, 255, 255));

        ritorno_volo_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ritorno_volo_label.setForeground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Benvenuto ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Prenota il tuo volo");

        meteo_list.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        meteo_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(meteo_list);

        log_out_button.setBackground(new java.awt.Color(255, 255, 255));
        log_out_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        log_out_button.setForeground(new java.awt.Color(26, 60, 160));
        log_out_button.setText("Log out");
        log_out_button.setActionCommand("Token scaduto - Premi per log out");
        log_out_button.setBorderPainted(false);
        log_out_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                log_out_buttonMouseClicked(evt);
            }
        });

        username_label.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        username_label.setForeground(new java.awt.Color(255, 255, 255));
        username_label.setText(" ");

        storico_button.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        storico_button.setForeground(new java.awt.Color(26, 60, 160));
        storico_button.setText("Replica");
        storico_button.setToolTipText("Esegui la stessa ricerca selezionata in \"Storico\"");
        storico_button.setBorderPainted(false);
        storico_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                storico_buttonMouseClicked(evt);
            }
        });

        volo_andata_label.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        volo_andata_label.setForeground(new java.awt.Color(255, 255, 255));
        volo_andata_label.setText("-");
        volo_andata_label.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        volo_ritorno_label.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        volo_ritorno_label.setForeground(new java.awt.Color(255, 255, 255));
        volo_ritorno_label.setText("-");
        volo_ritorno_label.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        mappa_button.setBackground(new java.awt.Color(255, 255, 255));
        mappa_button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mappa_button.setForeground(new java.awt.Color(26, 60, 160));
        mappa_button.setText("Mappa");
        mappa_button.setToolTipText("Visualizza la mappa");
        mappa_button.setBorderPainted(false);
        mappa_button.setEnabled(false);
        mappa_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mappa_buttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(origine_field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(origine_cerca_button, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(origine_box, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(storico_box, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(storico_button))
                            .addComponent(jLabel3)
                            .addComponent(ritorno_data_label)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passeggeri_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(cerca_button)
                                .addGap(18, 18, 18)
                                .addComponent(mappa_button)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ritorno_volo_label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(andata_volo_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(476, 476, 476))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(ritorno_prenota_button)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(volo_ritorno_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(destinazione_field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(destinazione_cerca_button, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(destinazione_box, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ritorno_data_data_label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ritorno_data_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(andata_ritorno_check)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(andata_data_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(username_label, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(andata_prenota_button)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(volo_andata_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(log_out_button)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(log_out_button))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(username_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(storico_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(storico_button))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(origine_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(origine_cerca_button))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(origine_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(destinazione_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(destinazione_cerca_button))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(destinazione_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(andata_data_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(andata_ritorno_check)
                        .addGap(10, 10, 10)
                        .addComponent(ritorno_data_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ritorno_data_data_label)
                            .addComponent(ritorno_data_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(volo_andata_label, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(andata_prenota_button))
                        .addGap(27, 27, 27)
                        .addComponent(andata_volo_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(ritorno_volo_label)
                                .addGap(84, 84, 84)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ritorno_prenota_button)
                            .addComponent(volo_ritorno_label, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 36, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(passeggeri_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cerca_button)
                            .addComponent(mappa_button))
                        .addGap(29, 29, 29))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void storico_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storico_buttonMouseClicked
        if(!storico.isEmpty()){
            int index = storico_box.getSelectedIndex();
            origine_field.setText(storico.get(index).getOrigineNome());
            destinazione_field.setText(storico.get(index).getDestinazioneNome());
        }
    }//GEN-LAST:event_storico_buttonMouseClicked

    private void ritorno_prenota_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ritorno_prenota_buttonMouseClicked
        prenota(voli_ritorno, ritorno_list);
    }//GEN-LAST:event_ritorno_prenota_buttonMouseClicked

    private void andata_prenota_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_andata_prenota_buttonMouseClicked
        prenota(voli_andata, andata_list);
    }//GEN-LAST:event_andata_prenota_buttonMouseClicked

    private void cerca_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerca_buttonMouseClicked
        andata_list.removeAll();
        ritorno_list.removeAll();
        andata_list.setModel(new DefaultListModel());
        ritorno_list.setModel(new DefaultListModel());
        voli_andata = new ArrayList<>();
        voli_ritorno = new ArrayList<>();
        volo_andata_label.setText("-");
        volo_ritorno_label.setText("-");
        
        String origine = aeroporti_andata.get(origine_box.getSelectedIndex()).getPlaceId();
        String destinazione = aeroporti_ritorno.get(destinazione_box.getSelectedIndex()).getPlaceId();
        String origineNome = origine_field.getText();
        String destinazioneNome = destinazione_field.getText();
        String numero_adulti = passeggeri_spinner.getValue().toString();
        String data_andata = new SimpleDateFormat("yyyy-MM-dd").format(andata_data_spinner.getValue());

        try {
            voli_andata = App.getVoli(token, origine, origineNome, destinazione, destinazioneNome, data_andata, numero_adulti);
            System.out.println(voli_andata.toString());
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Interfaccia.class.getName()).log(Level.SEVERE, null, ex);
        }
        riempiListaVoli(voli_andata, andata_list, volo_andata_label);

        if(ritorno_data_spinner.isEnabled()){
            String data_ritorno = new SimpleDateFormat("yyyy-MM-dd").format(ritorno_data_spinner.getValue());
            try {
                voli_ritorno = App.getVoli(token, destinazione, destinazioneNome, origine, origineNome, data_ritorno, numero_adulti);
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(Interfaccia.class.getName()).log(Level.SEVERE, null, ex);
            }
            riempiListaVoli(voli_ritorno, ritorno_list, volo_ritorno_label);
        }
        else {
            ritorno_list.setModel(new DefaultListModel());
            voli_ritorno = new ArrayList<>();
            volo_ritorno_label.setText("-");
        }

        setMeteo();
        setStorico();
        mappa_button.setEnabled(true);
    }//GEN-LAST:event_cerca_buttonMouseClicked

    private void andata_ritorno_checkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_andata_ritorno_checkMouseClicked
        if(andata_ritorno_check.isSelected() ){
            ritorno_data_spinner.setEnabled(true);
            ritorno_prenota_button.setEnabled(true);
            ritorno_data_label.setForeground(Color.WHITE);
            ritorno_data_data_label.setForeground(Color.WHITE);
        }else{
            ritorno_data_spinner.setEnabled(false);
            ritorno_prenota_button.setEnabled(false);
            ritorno_data_label.setForeground(Color.GRAY);
            ritorno_data_data_label.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_andata_ritorno_checkMouseClicked

    private void destinazione_cerca_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_destinazione_cerca_buttonMouseClicked
        aeroporti_ritorno = setAeroporti(destinazione_field, destinazione_box, aeroporti_ritorno);
    }//GEN-LAST:event_destinazione_cerca_buttonMouseClicked

    private void origine_cerca_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_origine_cerca_buttonMouseClicked
        aeroporti_andata = setAeroporti(origine_field, origine_box, aeroporti_andata);
    }//GEN-LAST:event_origine_cerca_buttonMouseClicked

    private void log_out_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_out_buttonMouseClicked
        token = null;
        this.setVisible(false);
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_log_out_buttonMouseClicked

    private void mappa_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mappa_buttonMouseClicked
        showMappa();
    }//GEN-LAST:event_mappa_buttonMouseClicked
    
    public void prenota(ArrayList<VoloResponse> voli_array, javax.swing.JList voli_list) {
        if(!voli_array.isEmpty()){
            int index = voli_list.getSelectedIndex(); 
            String url = voli_array.get(index).getBookingUrl();
            try {
                Desktop.getDesktop().browse(new URI(url));
                App.setPrenotazione(token, voli_array.get(index));
            } catch (URISyntaxException | IOException ex) {
                Logger.getLogger(Interfaccia.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
        
    public ArrayList<Aeroporto> setAeroporti(javax.swing.JTextField aeroporto_field, javax.swing.JComboBox<String> aeroporto_box, ArrayList<Aeroporto> aeroporti) {

        String aeroporto = aeroporto_field.getText();
        aeroporto_box.removeAllItems();
        
        aeroporti = App.getAeroporti(aeroporto);
                
        if (aeroporti.isEmpty()) {
            aeroporto_box.addItem("Nessun aeroporto trovato");
        } else {
            for (Aeroporto aero : aeroporti) {
                aeroporto_box.addItem(aero.getPlaceName());
            }
        }
        return aeroporti;
    }
    
     public void setStorico() {

        storico = App.getStorico(token);
        
        if (storico.isEmpty()) {
            storico_box.removeAllItems();
            storico_box.addItem("Nessuna ricerca effettuata");
        } else {
            storico_box.removeAllItems();
            for (VoloRequest ricerca : storico) {
                storico_box.addItem(ricerca.getOrigineNome() + " - " + ricerca.getDestinazioneNome());
            }
        }
    }
    
    public void setMeteo() {

        Object meteo_origine = App.getMeteo(origine_field.getText());
        Object meteo_destinazione = App.getMeteo(destinazione_field.getText());

        DefaultListModel meteo_listModel = new DefaultListModel();
        meteo_listModel.addElement(meteo_origine.toString());
        meteo_listModel.addElement(meteo_destinazione.toString());
        meteo_list.setModel(meteo_listModel);
        meteo_list.setSelectionModel(new DisabledItemSelectionModel());
        meteo_list.setVisibleRowCount(2);
    }
    
    public void showMappa(){
        String origine = aeroporti_andata.get(origine_box.getSelectedIndex()).getPlaceName();
        String destinazione = aeroporti_ritorno.get(destinazione_box.getSelectedIndex()).getPlaceName();
        String url = App.getMappa(origine, destinazione);
        new Mappa(url);
    }

    public void riempiListaVoli(ArrayList<VoloResponse> voli, javax.swing.JList voli_list, javax.swing.JLabel volo_label){
        DefaultListModel listModel = new DefaultListModel();
        
        if (voli.isEmpty()) {
            listModel.addElement("Nessun volo trovato");
            voli_list.setSelectionModel(new DisabledItemSelectionModel());
        } else {
            for (VoloResponse volo : voli) {
                listModel.addElement(volo.toString());
            }
            voli_list.setSelectionModel(new DefaultListSelectionModel());

        }

        voli_list.setModel(listModel);
        voli_list.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        voli_list.setVisibleRowCount(5);
        
        ListSelectionListener listSelectionListener = new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent listSelectionEvent) {
                JList list = (JList) listSelectionEvent.getSource();
                int index = list.getSelectedIndex();
                if(!voli.isEmpty() && index != -1 ){
                    String msg = "<html>Volo N." + voli.get(index).getNumeroVolo() + " - [" + voli.get(index).getAgentePrenotazione() + "] Prezzo: " + voli.get(index).getPrezzo() + "\u20ac";
                    if(App.isSconto(token)){
                        Float prezzoSconto = Float.parseFloat(voli.get(index).getPrezzo());
                        prezzoSconto = prezzoSconto - (prezzoSconto/20);
                        msg += " (<font color='green'> " + String.format ("%.2f", prezzoSconto) + " \u20ac</font> )";
                    }
                    msg += "</html>";
                    volo_label.setText(msg);
                }else{
                    voli_list.removeListSelectionListener(this);
                }
                
            }
          };
        voli_list.addListSelectionListener(listSelectionListener);
            }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner andata_data_spinner;
    private javax.swing.JList<String> andata_list;
    private javax.swing.JButton andata_prenota_button;
    private javax.swing.JCheckBox andata_ritorno_check;
    private javax.swing.JLabel andata_volo_label;
    private javax.swing.JButton cerca_button;
    private javax.swing.JComboBox<String> destinazione_box;
    private javax.swing.JButton destinazione_cerca_button;
    private javax.swing.JTextField destinazione_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton log_out_button;
    private javax.swing.JButton mappa_button;
    private javax.swing.JList<String> meteo_list;
    private javax.swing.JComboBox<String> origine_box;
    private javax.swing.JButton origine_cerca_button;
    private javax.swing.JTextField origine_field;
    private javax.swing.JSpinner passeggeri_spinner;
    private javax.swing.JLabel ritorno_data_data_label;
    private javax.swing.JLabel ritorno_data_label;
    private javax.swing.JSpinner ritorno_data_spinner;
    private javax.swing.JList<String> ritorno_list;
    private javax.swing.JButton ritorno_prenota_button;
    private javax.swing.JLabel ritorno_volo_label;
    private javax.swing.JComboBox<String> storico_box;
    private javax.swing.JButton storico_button;
    private javax.swing.JLabel username_label;
    private javax.swing.JLabel volo_andata_label;
    private javax.swing.JLabel volo_ritorno_label;
    // End of variables declaration//GEN-END:variables
    String token;
    
}

class DisabledItemSelectionModel extends DefaultListSelectionModel {

    @Override
    public void setSelectionInterval(int index0, int index1) {
        super.setSelectionInterval(-1, -1);
    }
}




